module.exports = {
    "is":               require('nor-is'),
    "currency":         require('nor-currency'),
    "fs":               require('nor-fs'),
    "nopg":             require('nor-nopg'),
    "nopg-store":       require('nor-nopg-store'),
    "express":          require('nor-express'),
    "debug":            require('nor-debug'),
    "data":             require('nor-data'),
    "rest":             require('nor-rest'),
    "passport":         require('nor-passport'),
    "flags":            require('nor-flags'),
    "routes-json":      require('nor-routes-json'),
    "acl":              require('nor-acl'),
    "ref":              require('nor-ref'),
    "versions":         require('nor-versions'),
    "csv":              require('nor-csv'),
    "mailer":           require('nor-mailer'),
    "api-helpers":      require('nor-api-helpers'),
    "api-session":      require('nor-api-session'),
    "api-registration": require('nor-api-registration'),
    "api-profile":      require('nor-api-profile'),
    "newrelic":         require('nor-newrelic'),
    "github":           require('nor-github'),
    "rest-jquery":      require('jquery-nor-rest'),
    "prettified":       require('prettified'),
    "crypt3":           require('crypt3')
};
